### ISSUE TITLE
Texte werden nicht angezeigt

### ISSUE THREAD

**Issue by CoHyper** [KarlBogen/bootstrap4#1]
Bis auf "Newsletter-Anmeldung" wird im Template "Minty" ein paar Texte im Footer nicht angezeigt. Habe dir mal ein Screen gemacht.
![bug](https://user-images.githubusercontent.com/6321093/100769266-16aace80-33fc-11eb-8808-7180578b62cf.png)

**Comment by KarlBogen** [comment]
Hi CoHyper,
erstmal danke für dein Interesse.

Die verschiedenen Themes von Bootswatch sind ein Zusatzangebot im Theme Manager.
Der Nutzer kann unter anderem im Template Manager -> BS4 Konfiguration auch die CSS-Klasse der Footernavbar und die Hintergrundfarbe verändern.
Mir ist bewusst, dass Anzeigefehler bei den Themes auftreten, aber ich kann nicht auf alle Eventualitäten eingehen.

In diesem Fall würde die CSS-Anweisung helfen.
`#layout_footer .text-secondary {
    color: #fff !important;
}`

Ab Version 1.1.0 kann man eine Datei custom.css mit dem obigen Inhalt in den Ordner templates/bootstrap4/ legen.
Ist die Datei custom.css vorhanden, wird sie automatisch eingelesen.
