### ISSUE TITLE
Undefined variable $font-family-serif: _bootswatch.scss on line 30

### ISSUE THREAD

**Issue by Gulliver72** [KarlBogen/bootstrap4#5]
Wenn ich in Bootstrap 4 Theme-Einstellungen die Vorschau für das Theme Litera lade, erhalte ich folgende Fehlermeldung.

_Der Bootstrap 4 Template-Manager kann nicht wie gewünscht genutzt werden!
Dieser Fehler ist aufgetreten: Undefined variable $font-family-serif: _bootswatch.scss on line 30, at column 3 Call Stack: #0 import _bootswatch.scss custom.scss on line 8_

Bootstrap 4 Template-Manager - Version: 1.2.15

**Comment by KarlBogen** [comment]
Hallo Gulliver72,
da hast du einen Fehler entdeckt.
Bitte schau dir die Datei new_files/admin/includes/bs4_template_manager/themes/litera/_add.scss an,
dort habe ich die fehlende Zeile eingetragen.

`$font-family-serif: Georgia, Cambria, "Times New Roman", Times, serif !default;`

Gruß Karl
